// USER

// USER ACTIONS
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILUER = "LOGIN_USER_FAILUER";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILUER = "REGISTER_USER_FAILUER";



// Note action 
export const ADD_NOTE = "ADD_NOTE";
export const ADD_NOTE_SUCCESS = "ADD_NOTE_SUCCESS";
export const ADD_NOTE_FAILURE = "ADD_NOTE_FAILUER";
export const DELETE_NOTE = "DELETE_NOTE";
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS";
export const DELETE_NOTE_FAILURE = "DELETE_NOTE_FAILUER";



// on load application needed calls;

export const GET_BASIC_DATA = "GET_BASIC_DATA";


// sketch art 


export const GET_CONTACT_US_DATA = "GET_CONTACT_US_DATA";
export const GET_CONTACT_US_DATA_SUCCESS = "GET_CONTACT_US_DATA_SUCCESS";
export const GET_CONTACT_US_DATA_FAILURE = "GET_CONTACT_US_DATA_FAILURE";


// GALLARY 
export const GET_SKETCHART_GALLARY = "GET_SKETCHART_GALLARY";
export const GET_SKETCHART_GALLARY_SUCCESS = "GET_SKETCHART_GALLARY_SUCCESS";
export const GET_SKETCHART_GALLARY_FAILURE = "GET_SKETCHART_GALLARY_FAILURE";



// ADMIN
export const ADMIN_LOGIN = "ADMIN_LOGIN";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAILURE = "ADMIN_LOGIN_FAILURE";

// All User LIst 
export const GET_ALL_USER = "GET_ALL_USER";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAILURE = "GET_ALL_USER_FAILURE";


